### ISSUE TITLE
Transfer labels across omics

### ISSUE THREAD

**Issue by Kevis9** [QSong-github/scGCN#10]
Hi, QSong!
      I have some questions about the topic "Transfering labels across omics" mentioned in the paper. I can't find any code related to this topic in this repository, including Batch mixing entropy and Silhouette score these two evaluation metrics.         
     I want to know how you pre-process the data in multi-omics?  In the paper, the data process only mentions common gene features, but ATAC-seq doesn't have gene symbols.

**Comment by ahassien** [comment]
I would also be interested in this information in case you ended up finding the answer.
