### ISSUE TITLE
The format of the input data

### ISSUE THREAD

**Issue by 11051911** [QSong-github/scGCN#12]
When transferring cell labels within the dataset, you randomly select 50% of its cells as reference data, and apply the above method to learn the labels of the other 50% of cells as query data.
What should the input of the code be, is this random score already divided in the code, or is it randomly divided before entering the original data, and the format of the input data must be the same as given in the example?

**Comment by QSong-github** [comment]
If the data format is not same with the example version, you may need to adjust the processing code a bit to make sure downstream runs.
