### ISSUE TITLE
Issue while using GEO 108989 dataset.

### ISSUE THREAD

**Issue by rahulbhadani** [QSong-github/scGCN#4]
Hello Professor Song,
              I want to use the GEO108989 dataset with scGCN but I am having an issue.

Summary of the issue. While doing `python train.py`, I got the following error:

```
WARNING:tensorflow:From train.py:20: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

Traceback (most recent call last):
  File "train.py", line 42, in <module>
    FLAGS.dataset,rgraph=FLAGS.graph)
  File "/home/refulgent/VersionControl/scGCN/scGCN/utils.py", line 46, in load_data
    input_data(datadir,Rgraph=rgraph)
  File "/home/refulgent/VersionControl/scGCN/scGCN/data.py", line 64, in input_data
    temD_train, temL_train, test_size=0.1, random_state=1)
  File "/home/refulgent/anaconda3/envs/tf1x/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2176, in train_test_split
    default_test_size=0.25)
  File "/home/refulgent/anaconda3/envs/tf1x/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1861, in _validate_shuffle_split
    train_size)
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

```

Here are the steps I followed:

1. I downloaded count data from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE108989 and copied labels from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GSE108989&id=166188&db=GeoDb_blob163 to a file which can be downloaded from https://github.com/gravitogen/hosting_datasets/releases/download/geo108989/cell_labels.txt 
2. I used the following R code to generate `.RDS` files:
```
library(foreach)
library(Matrix)
library(stringr)
library(pracma)
library(RSpectra)
library(umap)
library(Rtsne)
library(bigstatsr)
library(data.table)
library(cluster)

# Folder count data and labels are
main_directory <- 'GSE108989'
file <- 'GSE108989_CRC.TCell.S11138.count.txt.gz'

# read count data
data <- read.table(gzfile(sprintf("%s/%s", main_directory, file)),sep="\t", header = TRUE)
rownames(data) <- make.names(data$symbol, unique = TRUE) 
data <- data[, -c(1, 2)]
data <- data[,sort(colnames(data))]

labelfile <- 'cell_labels.txt'
labels <- read.table(sprintf("%s/%s", main_directory, labelfile), sep = "\t", header = TRUE)
rownames(labels) <- labels$UniqueCell_ID
labels<- labels[sort(rownames(labels)),]
labels <- as.data.frame(labels[, -c(1, 2, 4)])
colnames(labels) <- c("type")

# ref_cols <- sample(ncol(data), size = round(ncol(data)/2))
# ref_data = data[,ref_cols, drop = FALSE]

# sample half of the data randomly as reference data
ref_cols <- sample(ncol(data), size = round(ncol(data)/2))
ref_data <- data[,ref_cols, drop = FALSE]
ref_labels <- as.data.frame(labels[ref_cols,])
colnames(ref_labels) <- c("type")


# Set remaining data as query data
query_data <- data[, -ref_cols, drop=FALSE]
query_labels <- as.data.frame(labels[-ref_cols,])
colnames(query_labels) <- c("type")


count108989.list <- list(query_data, ref_data)
label108989.list <- list(query_labels, ref_labels)

saveRDS(count108989.list, file = sprintf("%s/108989count5050_stat.RDS", main_directory))
saveRDS(label108989.list, file = sprintf("%s/108989label5050_stat.RDS", main_directory))

```
3. Then set the location of `.RDS` files in `data_preprocess.R` and ran the following commands:
```
Rscript data_preprocess.R

```
I also needed to change label1.csv and label2.csv to Label1.csv and Label2.csv
4. Then I ran 
```
python train.py
```

However, upon running `train.py`, I got the error shown above.
I am not sure what is the problem here.

Alternatively, if you have the script to process and generate `.RDS` from GEO108989, can you please provide that.

Thanks
Rahul

**Comment by QSong-github** [comment]
I ran the GEO108989 the same way with the example data, but I didn't keep that script. My suggestion here is you may need to input the GEO108989 data of the same format with the example data. Also, you need to check the saved data in middle process, to see whether they are correct/ same with examples. It looks like the error is not raised from the tool itself.

**Comment by rahulbhadani** [comment]
Thanks for your reply Professor Song, Can you please provide the output of `conda list` or `pip list` to see if I need a specific version of any package.
