### ISSUE TITLE
How to use enrichment and entropy scores to detect unknown cell types?

### ISSUE THREAD

**Issue by XiHuYan** [QSong-github/scGCN#6]
Thanks for sharing this excellent work!

When trying to use scGCN on my own datasets, I didn't known how to detect unknown cell types in the query datasets. After reading your code, I found that _**data_preprocess.R**_ produced _**statistical_scores.RDS**_ file but never use it. So, could you share your code that explicitly define unknown cell types in the query datasets.

**Comment by QSong-github** [comment]
Would you please check the supplementary file of scGCN paper that explicitly explains the way to identify unknown cells. Both scores are stored in the statistical_scores.RDS file.
