### ISSUE TITLE
Could you provide the Python version ?

### ISSUE THREAD

**Issue by FupaulHuang** [QSong-github/scGCN#8]
Hi, the scGCN is an interesting jobs. However, when I tried to run the example data, I met lots of errors and finally found that it was due to the version of Python. I suppose that the current version of scGCN was bulit under Python2, which can only insatll tensorflow >= 1.15.0 as well as <= 2.0.0 and is imcompatible. Therefore, when I used Python3 and installed  tensorflow >= 2.0.0, it failed. So, I think providing the Python version would be better.

By the way, when I tried to run the example data using Python3, I changed all "import tensorflow as tf" into "import tensorflow.compat.v1 as tf", and add "tf.disable_eager_execution()", it succeed. And I wonder whether it is reasonable?

**Comment by QSong-github** [comment]
python 3 tensorflow 1.15.0 version works.

**Comment by FupaulHuang** [comment]
However, tensorflow 1.15.0 seems to be only avaliable for Python 2, using pip(Python 3) to install tensorflow and 1.15.0 version could not be installed.

**Comment by ahassien** [comment]
@FupaulHuang in case you were still having this issue, I recently created a version of the code for the example data this is compatible with tensorflow 2
https://github.com/ahassien/scGCN_tensorflow2

**Comment by 11051911** [comment]
> @FupaulHuang如果您仍然遇到此问题，我最近为示例数据创建了一个代码版本，该版本与 TensorFlow 2 https://github.com/ahassien/scGCN_tensorflow2 兼容

那咱这个新版本的话能复现其余的数据吗，比如说和tensorflow1一样的效果

**Comment by QSong-github** [comment]
> @FupaulHuang in case you were still having this issue, I recently created a version of the code for the example data this is compatible with tensorflow 2 https://github.com/ahassien/scGCN_tensorflow2

Thanks for the work!
